logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.type.descriptor: TRACE
spring:
  datasource:
    password: nqmame852
    url: jdbc:mysql://localhost:3306/galactic_intruders?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true